<?php
namespace mjburgess\paydays;

use mjburgess\paydays\PayDates;
use mjburgess\paydays\Application;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 13:41:10.
 */
class CliEntryPointTest extends \PHPUnit_Framework_TestCase
{
    public function testFormatPaydays()
    {
        $pd = new PayDates(5, 2013);
        $pd->setPayDate(mktime(0,0,0,5,15,2013));
        $pd->setBonusDate(mktime(0,0,0,5,25,2013));

        $this->assertEquals(['2013, 5, 15, 25'], CliEntryPoint::formatPaydays([$pd]));
    }

    /**
     * @covers mjburgess\paydays\CliEntryPoint::main
     */
    public function testMain()
    {
        $header = "year, month, pay date, bonus date\n";
        $csv    = $header . implode("\n", CliEntryPoint::formatPaydays((new Application())->run()));

        ob_start();
        CliEntryPoint::main(['test', 'test.csv']);
		
        $this->assertEquals($csv, ob_get_clean());
    }
}
