<?php
namespace mjburgess\paydays;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 13:41:24.
 */
class PayDatesCollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PayDatesCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PayDatesCollection();
    }

    /**
     * @covers mjburgess\paydays\PayDatesCollection::fromExtendedRange
     */
    public function testFromExtendedRange()
    {
        $month = 1; $year = date('Y');
        foreach($this->object->fromExtendedRange(1, 24) as $paydates) {
            if($month == 13) { $month = 1; $year++; }

            $expected[] = [$month++, $year];
            $observed[] = [$paydates->getMonth(), $paydates->getYear()];
        }

        $this->assertEquals($expected, $observed);
    }

    /**
     * @covers mjburgess\paydays\PayDatesCollection::applyTransforms
     */
    public function testApplyTransforms()
    {
        $this->object = $this->object->fromExtendedRange(0, 24);
        $observed = $this->object->applyTransforms([function ($v) { return 1; }, function ($v) { return $v + 1; }]);

        $this->assertEquals(array_fill(0, 25, 2), $observed);
    }
}


