<?php
namespace mjburgess\paydays;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 13:41:20.
 */
class PayDatesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PayDates
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PayDates(5, 2013);
    }

    /**
     * @covers mjburgess\paydays\PayDates::getMonth
     */
    public function testGetMonth()
    {
        $this->assertEquals(5, $this->object->getMonth());
        $this->assertEquals(mktime(0,0,0,5,1,2013), $this->object->getMonth(true));
    }

    /**
     * @covers mjburgess\paydays\PayDates::getYear
     */
    public function testGetYear()
    {
        $this->assertEquals(2013, $this->object->getYear());
        $this->assertEquals(mktime(0,0,0,5,1,2013), $this->object->getYear(true));
    }

    /**
     * @covers mjburgess\paydays\PayDates::setBonusDate
     */
    public function testSetBonusDate()
    {
        $this->object->setBonusDate(15);
        $this->assertEquals(15, $this->object->getBonusDate());
    }

    /**
     * @covers mjburgess\paydays\PayDates::setPayDate
     */
    public function testSetPayDate()
    {
        $this->object->setPayDate(15);
        $this->assertEquals(15, $this->object->getPayDate());
    }

    /**
     * @covers mjburgess\paydays\PayDates::getPayDate
     */
    public function testGetPayDate()
    {
        $this->object->setPayDate(mktime(0,0,0,1,5,2013));
        $this->assertEquals('05-01-2013', $this->object->getPayDate('d-m-Y'));
    }

    /**
     * @covers mjburgess\paydays\PayDates::getBonusDate
     */
    public function testGetBonusDate()
    {
        $this->object->setBonusDate(mktime(0,0,0,1,5,2013));
        $this->assertEquals('05-01-2013', $this->object->getBonusDate('d-m-Y'));
    }
}
