<?php
namespace mjburgess\paydays\transform;

use mjburgess\paydays\condition\PassCondition;
use mjburgess\paydays\transform\PassDateTransform;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 13:53:00.
 */
class RuleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Rule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Rule(new PassCondition(), new PassDateTransform());
    }

    /**
     * @covers mjburgess\paydays\transform\Rule::apply
     */
    public function testApply()
    {
        $this->assertEquals(10, $this->object->apply(10));
        $this->assertEquals(0, $this->object->apply(0));
    }
}
