<?php
namespace mjburgess\paydays\transform;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 13:52:54.
 */
class WeekdayDateTransformTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers mjburgess\paydays\transform\WeekdayDateTransform::apply
     */
    public function testApply()
    {
        $o = (new WeekdayDateTransform(WeekdayDateTransform::MONDAY, WeekdayDateTransform::NEXT))->apply(time());
        $this->assertEquals(strtotime('next monday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::TUESDAY, WeekdayDateTransform::NEXT))->apply(time());
        $this->assertEquals(strtotime('next tuesday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::WEDNESDAY, WeekdayDateTransform::NEXT))->apply(time());
        $this->assertEquals(strtotime('next wednesday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::THURSDAY, WeekdayDateTransform::NEXT))->apply(time());
        $this->assertEquals(strtotime('next thursday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::FRIDAY, WeekdayDateTransform::NEXT))->apply(time());
        $this->assertEquals(strtotime('next friday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::MONDAY, WeekdayDateTransform::PREV))->apply(time());
        $this->assertEquals(strtotime('last monday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::TUESDAY, WeekdayDateTransform::PREV))->apply(time());
        $this->assertEquals(strtotime('last tuesday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::WEDNESDAY, WeekdayDateTransform::PREV))->apply(time());
        $this->assertEquals(strtotime('last wednesday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::THURSDAY, WeekdayDateTransform::PREV))->apply(time());
        $this->assertEquals(strtotime('last thursday'), $o);

        $o = (new WeekdayDateTransform(WeekdayDateTransform::FRIDAY, WeekdayDateTransform::PREV))->apply(time());
        $this->assertEquals(strtotime('last friday'), $o);

    }
}
