<?php
namespace mjburgess\paydays\transform;

use mjburgess\paydays\PayDates;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 13:52:49.
 */
class WeekdayTransformTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CoTransform
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CoTransform(new PassDateTransform(), new PassDateTransform());
    }

    /**
     * @covers mjburgess\paydays\transform\WeekdayTransform::getPayDate
     */
    public function testGetPayDate()
    {
        $this->assertEquals(10, $this->object->getPayDate(10));
    }

    /**
     * @covers mjburgess\paydays\transform\WeekdayTransform::getBonusDate
     */
    public function testGetBonusDate()
    {
        $this->assertEquals(10, $this->object->getPayDate(10));
    }

    /**
     * @covers mjburgess\paydays\transform\WeekdayTransform::__invoke
     */
    public function test__invoke()
    {
        $pd = new PayDates(5, 2013);
        $pd->setPayDate(15);
        $pd->setBonusDate(25);

        $pd = $this->object->__invoke($pd);
        $this->assertEquals(25, $pd->getBonusDate());
        $this->assertEquals(15, $pd->getPayDate());
    }
}
