<?php
namespace mjburgess\paydays\condition;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 13:53:17.
 */
class PassConditionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers mjburgess\paydays\condition\PassCondition::tryDate
     */
    public function testTryDate()
    {
        $this->assertEquals(true, (new PassCondition)->tryDate(time()));
		$this->assertEquals(false, (new PassCondition)->tryDate(0));
    }
}
