<?php
namespace mjburgess\paydays\condition;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-29 at 13:53:17.
 */
class WeekendConditionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var WeekendCondition
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WeekendCondition();
    }

    /**
     * @covers mjburgess\paydays\condition\WeekendCondition::tryDate
     */
    public function testTryDate()
    {
        $this->assertEquals(false, $this->object->tryDate(strtotime('next sunday')));
        $this->assertEquals(false, $this->object->tryDate(strtotime('next sunday')));

        $this->assertEquals(true, $this->object->tryDate(strtotime('next monday')));
        $this->assertEquals(true, $this->object->tryDate(strtotime('next tuesday')));
        $this->assertEquals(true, $this->object->tryDate(strtotime('next wednesday')));
        $this->assertEquals(true, $this->object->tryDate(strtotime('next thursday')));
        $this->assertEquals(true, $this->object->tryDate(strtotime('next friday')));
    }
}
